trigger:
- main

pool:
  vmImage: 'windows-latest'

stages:

- stage: Build
  displayName: 'Build'

  jobs:
  - job: BuildJob

    steps:

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.11'

    - script: |
        pip install -r requirements.txt
      workingDirectory: Testing
      displayName: 'Install dependencies'

- stage: Test
  displayName: 'Run Test'
  dependsOn: Build

  jobs:
  - job: TestJob

    strategy:
      matrix:

        Chrome:
          browser: chromium

        Firefox:
          browser: firefox

    steps:

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.11'

    - script: 
        pip install -r requirements.txt
      workingDirectory: Testing
      displayName: 'Install dependencies'

    - script: 
        pytest --browser $(browser) --junitxml=test-results.xml
      workingDirectory: Testing
      displayName: 'Run pytest'

    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'Testing/test-results.xml'
        testRunTitle: 'Pytest - $(browser)'
      condition: succeededOrFailed()