
trigger:
- main

strategy:
  matrix:
  
    Windows_Chrome:
      vmImage: windows-latest
      browser: chromium

    # Windows_Firefox:
    #   vmImage: windows-latest
    #   browser: firefox

    # Ubuntu_Chrome:
    #   vmImage: ubuntu-latest
    #   browser: chromium

    # Ubuntu_Firefox:
    #   vmImage: ubuntu-latest
    #   browser: firefox

  # maxParallel: 2

pool:
  vmImage: $(vmImage)
  
steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

- script: 
    pip install -r requirements.txt
  workingDirectory: Testing
  displayName: 'Install dependencies'

- script: 
    pytest --browser $(browser) --junitxml=test-results.xml
  workingDirectory: Testing
  displayName: 'Run pytest'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFiles: 'Testing/test-results.xml'
    testRunTitle: 'Pytest Results'
  condition: or(succeeded(), failed())

